import { fetchTrendsAction } from "@/app/actions/trend-actions";
import { TrendTable } from "@/components/trend-table";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";
import { TrendStatus } from "@prisma/client";

async function getDashboardData() {
  const [pending, approved, rejected, latestTrends, recentContent, pendingJobs] =
    await Promise.all([
      prisma.trend.count({ where: { status: TrendStatus.PENDING } }),
      prisma.trend.count({ where: { status: TrendStatus.APPROVED } }),
      prisma.trend.count({ where: { status: TrendStatus.REJECTED } }),
      prisma.trend.findMany({
        orderBy: { fetchedAt: "desc" },
        take: 30,
      }),
      prisma.generatedContent.findMany({
        orderBy: { createdAt: "desc" },
        take: 5,
      }),
      prisma.postingJob.count({
        where: {
          status: {
            in: ["PENDING", "FAILED"],
          },
        },
      }),
    ]);

  return {
    pending,
    approved,
    rejected,
    latestTrends,
    recentContent,
    pendingJobs,
  };
}

export default async function DashboardPage() {
  const data = await getDashboardData();

  return (
    <div className="stack">
      <header className="page-heading">
        <h1 className="page-heading__title">Autonomous Social Intelligence</h1>
        <p className="page-heading__subtitle">
          Discover emerging trends, generate cross-platform content, and deploy
          campaigns automatically from a single command center.
        </p>
      </header>

      <section className="hero">
        <div className="grid three">
          <div>
            <div className="section__title">Pending Review</div>
            <div className="hero__title">{data.pending}</div>
            <p className="hero__description">
              Trends harvested in the last 24 hours awaiting approval.
            </p>
          </div>
          <div>
            <div className="section__title">Approved Content</div>
            <div className="hero__title">{data.approved}</div>
            <p className="hero__description">
              Ready-to-post creative assets generated by the AI agent.
            </p>
          </div>
          <div>
            <div className="section__title">Queued Jobs</div>
            <div className="hero__title">{data.pendingJobs}</div>
            <p className="hero__description">
              Scheduled autopost tasks across configured social channels.
            </p>
          </div>
        </div>
      </section>

      <form action={fetchTrendsAction} className="card">
        <h2 className="card__title">Ingest New Trends</h2>
        <p className="card__subtitle">
          Pull real-time signals from Google, Reddit, X, YouTube, and NewsAPI
          (configure API keys in settings). The agent unifies results and keeps
          deduplicated records.
        </p>
        <div className="form-row">
          <div className="form-group">
            <label>Language</label>
            <select name="language" className="select" defaultValue="en">
              <option value="">Auto</option>
              <option value="en">English</option>
              <option value="ur">Urdu</option>
            </select>
          </div>
          <div className="form-group">
            <label>Region</label>
            <input
              name="region"
              className="input"
              placeholder="US, PK, GB..."
            />
          </div>
          <div className="form-group">
            <label>Category</label>
            <input
              name="category"
              className="input"
              placeholder="technology, sports, entertainment..."
            />
          </div>
        </div>
        <button className="button" type="submit">
          Fetch Trends
        </button>
      </form>

      <TrendTable trends={data.latestTrends} />

      <section className="card">
        <h2 className="card__title">Latest AI Content</h2>
        <p className="card__subtitle">
          Quick view of recently generated posts. Manage full lifecycle in the
          Content workspace.
        </p>
        <div className="stack">
          {data.recentContent.length === 0 ? (
            <div className="empty-state">
              No generated content yet. Approve a trend to spin up AI copy.
            </div>
          ) : (
            data.recentContent.map((content) => (
              <div key={content.id} className="card" style={{ marginTop: 0 }}>
                <div className="stack-sm">
                  <div className="chips">
                    <span className="pill badge--platform">
                      Platform: {content.platform}
                    </span>
                    <span className="pill">
                      Status: {content.status.toLowerCase()}
                    </span>
                    {content.scheduledFor && (
                      <span className="pill">
                        Scheduled: {formatDate(content.scheduledFor)}
                      </span>
                    )}
                  </div>
                  <p>{content.body.slice(0, 240)}...</p>
                  <span className="muted">
                    Generated {formatDate(content.createdAt)}
                  </span>
                </div>
              </div>
            ))
          )}
        </div>
      </section>
    </div>
  );
}
